steps:
  # Docker Build & Push
  - name: 'gcr.io/cloud-builders/gcloud'
    script: |
      gcloud builds submit --tag "asia-south1-docker.pkg.dev/team-medy-buddy/netra-source/netra:${TAG}"
    env:
     - 'TAG=$SHORT_SHA'
   
  # Application deployment
  - name: 'gcr.io/cloud-builders/gcloud'
    script: |
      gcloud run deploy netra --image "asia-south1-docker.pkg.dev/team-medy-buddy/netra-source/netra:${TAG}" --region us-central1 
    env:
     - 'TAG=$SHORT_SHA'
